### ISSUE TITLE
options names

### ISSUE THREAD

**Issue by scottcorgan** [krainboltgreene/snabbdom-helpers#1]
What do you think about `data` -> `attributes` and `content` -> `children`.

I wasn't sure your naming decisions, but it makes sense.

**Comment by krainboltgreene** [comment]
@scottcorgan `data` is literally the https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes attribute.

I need to update the readme to reflect this or change it internally. I'd love to just do away with non-root level property descriptions.

``` javascript
img({
  src: "/frame.jpg",
  title: "A frame",
  on: {
   click: boom
  },
  style: {
    "background-color": "red"
  },
})
```

The problem is that there's no clear way to decide what is `attrs` or what is `props`. I can't even really tell the difference between the two, honestly.

But for now you have to do:

``` javascript
img({
  props: {
    src: "/frame.jpg",
    title: "A frame",
  },
  on: {
   click: boom
  },
  style: {
    "background-color": "red"
  },
})
```

That said, `content` -> `children` is perfectly fine. It'll go out in 4.0.0.
